### ISSUE TITLE
Deprecate this method of running notebooks

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/datalab-jupyter#10]
Per the README, the original goals of this project were:

1. configuration for jupytext, to support easier code review
2. cross-platform startup scripts
3. best practice folder structure and documentation

We don't practically support it any more, and it is [causing problems](https://github.com/ebmdatalab/datalab-jupyter/issues/9) for team members who are still using it.

And aside from the specific problems, it results in massive git repos (e.g. 740M to support running what is essentially a few lines of code) and massive docker images.

## Configuration for jupytext, to support easier code review

I think this is now solved well-enough by this (currently-opt-in) feature:
![image](https://github.com/ebmdatalab/datalab-jupyter/assets/211271/c45992e0-56de-46b5-9928-916a538161f4)

## Cross-platform startup scripts

[The startup script](https://github.com/ebmdatalab/improvement_radar_prototype/blob/master/run.py) does the following:

* Builds a new docker image. The idea is that a user could just edit `requirements.txt` inside the docker image, which was mounted as a local directory, and forget about it.
* Starts docker, and waits for it to be ready, and tells the user how to shut it down

The main point here is just that maintaining a python environment in Windows is still a massive PITA. There are two parts to this - grokking virtual environments (it'd be nicer if they don't have to do this at all); and installing certain packages (e.g. GIS-related ones) is often a *nightmare* (but this _may_ have got better in the last 7 years)

However, it's turned out that "try to make this easy" is even more of a PITA.

The Dockerfile also attempts some other automagic things, beyond diffable python: in particular, it manipulates `sys.path` to guarantee that `lib/` is available from the notebook (that is, `import foo` will work, given a module at `lib/foo.py`).

Alternatives:

* Support users in maintaining their local Windows. We do [aim to support this as a route for installing OpenSAFELY](https://docs.opensafely.org/getting-started/#__tabbed_3_2), too, so keeping common knowledge and documentation about this up to date is perhaps not the hassle it seemed in 2017 when this was written. To work out if this is even worth considering, we would first need to check we can install all the packages needed in any currently live notebooks (get a list off Clinical Informatics team)
* Continue to support a Docker-first option, but don't try to do any magic; expect users to learn to run Docker commands directly (and maintain documentation about this)

## Best practice folder structure and documentation

This could be maintained by a new Github template, or just some documentation somewhere. Given we generally use notebooks for fast prototyping, I don't think it needs to be very heavy. We probably just need to document best practice around package management (python version, requirements.in).

**Comment by sebbacon** [comment]
When resolved, we should remember to archive this repo (and add a big warning text at the top)

**Comment by evansd** [comment]
Note to self that there's lots of code/logic worth cribbing from opensafely-cli around running Jupyter notebooks locally:
https://github.com/opensafely-core/opensafely-cli/blob/main/opensafely/jupyter.py

**Comment by evansd** [comment]
I think this is now resolved by:
 * https://github.com/ebmdatalab/datalab-notebook-template/pull/46

That PR makes the notebook template no longer depend on the Docker image built by this repo. So I _think_ this repo can now be archived.
