### ISSUE TITLE
Cannot run (or upgrade) notebooks

### ISSUE THREAD

**Issue by sebbacon** [ebmdatalab/datalab-jupyter#9]
Taking [this repo](https://github.com/ebmdatalab/improvement_radar_prototype) as an example.

When Rich uses `run.exe` to launch the notebook, he gets this ([full log](https://gist.github.com/sebbacon/73147f62d4ef6ca60a720a1cec8e8bbc)) from the python (`run.py`) invoked:

    ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

And this error in the Docker logs:

    Can't cd to /home/app/notebook

He also has an error related to `diffable_python`: Unexpected error while using file `

Related, Rich has tried to upgrade jupyterlab, mainly because he wants to "use notebook tags to hide stuff from nbconvert; and "to update the BQ library, in order to hide stuff" (more info needed). Like this :

    pip-compile --upgrade-package jupyterlab 
    pip-sync

**Comment by sebbacon** [comment]
There are two things we need to do as a result of this bug report.

* Unstick Rich in the first instance. The priority is improvement-radar (linked above) as he needs to install extra packages, and can't
* Deprecate this way of making notebooks. See #10 

For the first point, some options are:

1. Work out how to upgrade jupyter notebooks, which looks like it involves untangling legacy configuration (and could also optionally include excising the diffable_python stuff)
2. Migrate to a non-dockerised, new approach (which could be the minimum just to get going, but inform best practice for #10)

**Comment by sebbacon** [comment]
Reproducing on Linux:

* vanilla (i.e. just clone and `run.py`) build process works fine in Linux ([logs](https://gist.github.com/sebbacon/ecb2b4be55ba6eb3e287b61fb5304219))
* Local upgrade of jupyterlab [fails - (log)](https://gist.github.com/sebbacon/7924bbfb6855053486e4122c6a172214)
  * the fix is `export RPY2_CFFI_MODE=ABI` before the `pip-compile` step.
* But then running with `python run.py` (i.e. via Docker) [fails](https://gist.github.com/sebbacon/bfeb45541db5f8faa684af3e78477451) with `Waiting for Jupyter to be ready on port 32769 ... ConnectionRefusedError: [Errno 111] Connection refused`
  * The proximate cause of which is the same `bin/sh: 1: cd: can't cd to /home/app/notebook` as mentioned in the original report
  
Next, I would experiment with changing the config supplied to the notebook, to remove the diffable python stuff.

**Comment by evansd** [comment]
Rich is now successfully unstuck:
 * https://github.com/ebmdatalab/improvement_radar_prototype/pull/4
